// One entry per family: the name shown on the starred list and the one-line method shown after a miss.
// `lesson` names the lesson that teaches the method, when one exists.
const F = (name, method, lesson) => ({ name, method, lesson });
export const FAMILIES = {
  // poker
  pot_odds: F("Pot odds", "call / (pot + call). The pot already includes their bet.", "pot_odds_three_ways"),
  "outs_equity:1": F("Outs, one card to come", "outs x 2, or exactly outs / 46.", "rule_of_4_and_2"),
  "outs_equity:2": F("Outs, two cards to come", "outs x 4, minus (outs - 8) when outs are above 8. Exact: 1 - (miss)(miss).", "rule_of_4_and_2"),
  ev_call: F("EV of a call", "win% x pot minus lose% x call."),
  implied_odds: F("Implied odds", "call / win% is the pot you need; subtract what is there after your call."),
  "combos:pair": F("Combos: pocket pair", "4 choose 2 = 6."),
  "combos:suited": F("Combos: suited hand", "One per suit = 4."),
  "combos:offsuit": F("Combos: offsuit hand", "16 total minus 4 suited = 12."),
  "combos:any": F("Combos: any two ranks", "4 x 4 = 16."),
  "combos:pair_blocked": F("Combos: pair with a blocker", "3 left, choose 2 = 3."),
  "combos:any_blocked": F("Combos: two ranks with a blocker", "3 x 4 = 12."),
  "pot_odds_bet:third": F("Third-pot bet", "bet / (pot + 2 x bet): a third-pot bet needs 20%.", "pot_odds_three_ways"),
  "pot_odds_bet:half": F("Half-pot bet", "bet / (pot + 2 x bet): a half-pot bet needs 25%.", "pot_odds_three_ways"),
  "pot_odds_bet:twothirds": F("Two-thirds to three-quarter pot bet", "bet / (pot + 2 x bet): about 29% to 30%.", "pot_odds_three_ways"),
  "pot_odds_bet:pot": F("Pot-sized bet", "bet / (pot + 2 x bet): a pot-sized bet needs 33%.", "pot_odds_three_ways"),
  "pot_odds_bet:over": F("Overbet", "bet / (pot + 2 x bet): 1.5x pot needs 37.5%, 2x pot needs 40%.", "pot_odds_three_ways"),
  bluff_break_even: F("Bluff break-even", "bet / (pot + bet). Half-pot bluff needs a fold one time in three.", "pot_odds_three_ways"),
  pot_odds_decision: F("Call or fold", "Compare chance to hit with call / (pot + call).", "pot_odds_three_ways"),
  // quick
  percent_of: F("Percent of a number", "Take 10%, then scale. 1% for the awkward ones.", "percent_scaling"),
  fraction_to_decimal: F("Fraction to decimal", "Know 1/n, multiply by the top.", "fractions_worth_knowing"),
  "multiply_shortcuts:x11": F("Multiply by 11", "Split the digits, put their sum in the middle, carry if needed.", "multiply_by_11"),
  "multiply_shortcuts:sq5": F("Squares ending in 5", "tens x (tens + 1), then append 25.", "squares_ending_in_5"),
  "multiply_shortcuts:x25": F("Multiply by 25", "Divide by 4, then x 100.", "multiply_by_5_25_50"),
  "growth_rate:pct": F("Growth rate", "change / start.", "percent_scaling"),
  "growth_rate:double": F("Years to double", "72 / rate.", "rule_of_72"),
  "back_of_envelope:multiple": F("EV/EBITDA multiple", "EV / EBITDA.", "multiples_and_yields"),
  "back_of_envelope:ebitda": F("EBITDA from a margin", "revenue x margin.", "percent_scaling"),
  "back_of_envelope:mktcap": F("Market cap", "price x shares.", "millions_and_billions"),
  "back_of_envelope:interest": F("Interest expense", "debt x rate.", "percent_scaling"),
  // banking
  equity_value: F("Equity value from EV", "EV - debt + cash."),
  ev_from_equity: F("EV from market cap", "market cap + debt - cash."),
  multiple_to_yield: F("Multiple to yield", "1 / multiple.", "multiples_and_yields"),
  pe_ratio: F("P/E ratio", "price / EPS.", "multiples_and_yields"),
  dividend_yield: F("Dividend yield", "dividend / price.", "percent_scaling"),
  after_tax_debt: F("After-tax cost of debt", "rate x (1 - tax)."),
  wacc: F("Blended cost of capital", "equity% x cost of equity + debt% x cost of debt x (1 - tax)."),
  capm: F("Cost of equity (CAPM)", "risk-free + beta x premium."),
  discount_one_year: F("Discount one year", "divide by (1 + rate)."),
  perpetuity: F("Perpetuity value", "cash flow / (rate - growth)."),
  lbo_return: F("Buyout yearly return", "Anchors: 2x in 5 years is 15%, 3x in 5 is 25%; rule of 72 for doubling.", "rule_of_72"),
  lbo_moic: F("Buyout multiple", "equity out / equity in."),
  accretion: F("Accretive or dilutive", "All-stock: buyer's P/E above target's is accretive.", "multiples_and_yields"),
  interest_coverage: F("Interest coverage", "EBITDA / interest."),
  bank_spread: F("Bank spread", "(lend rate - deposit rate) x loans."),
  // accounting
  balance_sheet: F("Balance sheet", "equity = assets - liabilities."),
  eps: F("Earnings per share", "net income / shares."),
  net_income_from_ebit: F("Net income from EBIT", "(EBIT - interest) x (1 - tax)."),
  working_capital: F("Working capital", "current assets - current liabilities."),
  dep_net_income: F("Depreciation up: net income", "falls by amount x (1 - tax)."),
  dep_cash: F("Depreciation up: cash", "rises by amount x tax."),
  // moose / novyx / betting / energy
  contribution_margin: F("Contribution margin ($)", "price - product cost - shipping - fee% of price.", "percent_scaling"),
  "contribution_margin:pct": F("Contribution margin (%)", "margin $ / price.", "percent_scaling"),
  payback_months: F("Payback months", "CAC / (margin per order x orders per month)."),
  break_even_units: F("Break-even units", "fixed costs / margin per unit."),
  discount_trap: F("Discount trap", "margin / (margin - discount) - 1."),
  roas_to_return: F("Ad return", "ROAS x margin - 1."),
  customer_value: F("Customer value", "margin per order x orders."),
  rebooking_revenue: F("Rebooking revenue", "visits x rate x ticket."),
  unrealized_revenue: F("Unrealized revenue", "(target rate - rate) x visits x ticket."),
  rate_card: F("Rate card price", "cost / (1 - margin).", "percent_scaling"),
  pipeline_revenue: F("Pipeline revenue", "leads x close rate x ticket."),
  lifetime_value: F("Lifetime value", "ticket x visits per year x years."),
  american_to_prob: F("American odds to chance", "+odds: 100 / (odds + 100). -odds: odds / (odds + 100)."),
  decimal_to_prob: F("Decimal odds to chance", "1 / odds."),
  fraction_to_decimal_odds: F("Fractional to decimal odds", "top / bottom + 1."),
  remove_vig: F("Remove the vig", "side / (side + other side)."),
  bet_ev: F("EV of a bet", "p x stake x (odds - 1) minus (1 - p) x stake."),
  kelly: F("Kelly fraction", "(p x (odds - 1) - (1 - p)) / (odds - 1)."),
  oil_revenue: F("Quarterly oil revenue", "barrels a day x price x 90.", "millions_and_billions"),
  netback: F("Netback", "price minus costs per barrel."),
  decline: F("Decline", "output x (1 - rate)."),
  reserve_life: F("Reserve life", "reserves / (daily output x 365).", "millions_and_billions"),
  breakeven_price: F("Break-even oil price", "(opex + capex) / (1 - royalty)."),
};
Object.assign(FAMILIES, {
  count_outs: F("Count the outs", "Add the draws, subtract cards counted twice.", "count_the_outs"),
  pot_odds_ratio: F("Pot odds as a ratio", "pot to call; percent is 1 / (ratio + 1).", "pot_odds_three_ways"),
  price_out_draw: F("Pricing out a draw", "bet / (pot + 2 x bet) must beat the draw's chance.", "pot_odds_three_ways"),
  near_100: F("Near-100 products", "front: one number minus the other's gap; back: gaps multiplied.", "near_100"),
  halve_double: F("Halve and double", "halve the even one, double the other.", "halve_and_double"),
  split_multiply: F("Split the hard one", "tens x b, then ones x b, add.", "split_the_hard_one"),
  round_adjust: F("Round, then adjust", "round x b, then add or subtract gap x b.", "round_and_adjust"),
  "divide_shortcuts:d4": F("Divide by 4", "halve twice.", "divide_by_4_and_8"),
  "divide_shortcuts:d8": F("Divide by 8", "halve three times.", "divide_by_4_and_8"),
  "divide_shortcuts:d5": F("Divide by 5", "double, then divide by 10.", "divide_by_5_25_50"),
  "divide_shortcuts:d25": F("Divide by 25", "times 4, then divide by 100.", "divide_by_5_25_50"),
  "divide_shortcuts:d50": F("Divide by 50", "double, then divide by 100.", "divide_by_5_25_50"),
  reverse_percent: F("Reverse percent", "part / (percent as a decimal).", "percent_scaling"),
  percent_chain: F("Percent chain", "multiply (1 + a)(1 + b), then subtract 1.", "percent_scaling"),
  unit_juggle: F("Units: millions and billions", "convert to one unit, multiply the plain numbers, then the units.", "millions_and_billions"),
  accretion_mix: F("Accretion, mixed payment", "target's yield vs blended cost of stock (earnings yield) and after-tax debt.", "multiples_and_yields"),
  synergies_breakeven: F("Break-even synergies", "premium / multiple."),
  dcf_two_year: F("Two-year DCF", "each cash flow / (1 + r)^year, terminal value in the last year."),
  debt_paydown: F("Debt paydown", "debt - paydown x years."),
  cap_table: F("Dilution", "own x pre / (pre + raise)."),
});
const EVENTS = ["Depreciation up: net income", "Depreciation up: cash", "Inventory up: net income", "Inventory up: cash", "Share issue: assets", "Share issue: net income", "New debt: equity", "Dividend: equity", "Dividend: net income", "Interest up: cash", "Receivables up: cash", "Payables up: cash", "Invoice collected: net income", "Factory bought: net income"];
EVENTS.forEach((n, i) => { FAMILIES[`statement_direction:${i}`] = F(n, "Ask which statement the event touches first, then follow it across."); });
