// One entry per family: the name shown on the starred list and the one-line method shown after a miss.
// `lesson` names the lesson that teaches the method, when one exists.
const F = (name, method, lesson) => ({ name, method, lesson });
export const FAMILIES = {
  // poker, advanced
  ...Object.fromEntries(["third", "half", "twothirds", "pot", "over"].map((k) => [`mdf:${k}`, F(`Defend against a ${{ third: "third-pot", half: "half-pot", twothirds: "two-thirds-pot", pot: "pot-sized", over: "1.5x-pot" }[k]} bet`, "pot / (pot + bet). Third 75%, half 67%, two-thirds 60%, pot 50%, 1.5x 40%.", "defense_and_bluffs")])),
  ...Object.fromEntries(["third", "half", "twothirds", "pot", "over"].map((k) => [`bluff_ratio:${k}`, F(`Bluff share for a ${{ third: "third-pot", half: "half-pot", twothirds: "two-thirds-pot", pot: "pot-sized", over: "1.5x-pot" }[k]} bet`, "bet / (pot + 2 x bet). Third 20%, half 25%, two-thirds 29%, pot 33%, 1.5x 37.5%.", "defense_and_bluffs")])),
  spr: F("Stack-to-pot ratio", "Smaller stack / pot. Under about 3, one pair commits; above about 10, it does not.", "stacks_and_sizing"),
  geo_sizing: F("Geometric bet sizing", "(1 + 2f)^streets = 1 + 2 x SPR. Two pot bets cover SPR 4, three cover SPR 13.", "stacks_and_sizing"),
  "board_combos:pair": F("Pair combos with cards showing", "Unseen of the rank, choose 2: 3 left is 3, 2 left is 1.", "combos_on_board"),
  "board_combos:unpaired": F("Two-rank combos with cards showing", "Unseen of one rank x unseen of the other.", "combos_on_board"),
  semibluff_ev: F("Semi-bluff value", "fold x pot + call x (equity x final pot - bet).", "semibluff_math"),
  semibluff_breakeven: F("Semi-bluff break-even folds", "loss when called / (pot + loss when called). No equity: bet / (pot + bet).", "semibluff_math"),
  "preflop_anchor:aa_kk": F("AA against KK", "About 82%.", "preflop_anchors"),
  "preflop_anchor:pair_vs_lower": F("Pair against a lower pair", "About 80%.", "preflop_anchors"),
  "preflop_anchor:pair_vs_overs": F("Pair against two overcards", "About 55%, the coin flip.", "preflop_anchors"),
  "preflop_anchor:dominated": F("Dominated kicker", "AK against AQ: about 74%.", "preflop_anchors"),
  "preflop_anchor:overs_vs_unders": F("Two overs against two unders", "About 60%.", "preflop_anchors"),
  "preflop_anchor:pair_vs_one_over": F("Pair against one over, one under", "About 70%.", "preflop_anchors"),
  // valuation
  ufcf: F("Unlevered free cash flow", "EBIT x (1 - t) + D&A - capex - increase in working capital.", "ufcf_build"),
  tv_exit_multiple: F("Terminal value by exit multiple", "Final-year EBITDA x the peer multiple.", "terminal_value_two_ways"),
  tv_perpetuity_vs_exit: F("Perpetuity vs exit multiple", "FCF x (1 + g) / (r - g), then compare to the multiple's number.", "terminal_value_two_ways"),
  implied_growth: F("Implied growth from a multiple", "g = (TV x r - FCF) / (TV + FCF).", "terminal_value_two_ways"),
  "mid_year_direction:0": F("Mid-year convention: direction", "Half a year less discounting raises value.", "terminal_value_two_ways"),
  "mid_year_direction:1": F("Mid-year convention: which is more accurate", "Cash arrives through the year, so mid-year.", "terminal_value_two_ways"),
  "mid_year_direction:2": F("Mid-year convention: how much", "About (1 + r)^0.5 - 1, so about 5% at a 10% rate.", "terminal_value_two_ways"),
  comps_implied_ev: F("Comps to a share price", "Multiple x EBITDA = EV; minus net debt; divide by shares.", "comps_chain"),
  multiple_translate: F("Revenue multiple to EBITDA multiple", "EV/EBITDA = (EV/Revenue) / margin.", "comps_chain"),
  pe_from_ev_ebitda: F("EV/EBITDA to P/E", "EV - net debt = equity; / net income.", "comps_chain"),
  // accounting walks
  walk_depreciation_cash: F("Depreciation walk: cash", "Cash is up by depreciation x tax rate.", "three_statement_walk"),
  "walk_inventory_writedown:cash": F("Write-down: cash", "Cash is up by the write-down x tax rate.", "three_statement_walk"),
  "walk_inventory_writedown:equity": F("Write-down: equity", "Equity is down by the write-down x (1 - t).", "three_statement_walk"),
  "walk_sell_inventory:ni": F("Sell inventory: net income", "(Revenue - cost) x (1 - t).", "three_statement_walk"),
  "walk_sell_inventory:cash": F("Sell inventory: cash", "Revenue received minus tax paid; the cost is non-cash now.", "three_statement_walk"),
  "walk_capex_cash:cash": F("Capex walk: cash", "Minus the purchase, plus depreciation x tax rate.", "three_statement_walk"),
  "walk_capex_cash:ni": F("Capex walk: net income", "Minus depreciation x (1 - t).", "three_statement_walk"),
  walk_debt_raise: F("Debt raise walk", "Plus the debt, minus interest x (1 - t).", "three_statement_walk"),
  "walk_buyback:0": F("Buyback: equity", "Down by the amount bought back.", "three_statement_walk"),
  "walk_buyback:1": F("Buyback: net income", "No change. It is a financing event.", "three_statement_walk"),
  "walk_buyback:2": F("Buyback: assets", "Cash down by the amount.", "three_statement_walk"),
  // deals
  sources_uses_equity: F("Sources and uses", "Equity = price + fees - debt.", "paper_lbo_pieces"),
  "leverage_turns:total": F("Turns of leverage: total debt", "Senior turns + sub turns, times EBITDA.", "paper_lbo_pieces"),
  "leverage_turns:rate": F("Turns of leverage: blended rate", "Weight each tranche's rate by its share of debt.", "paper_lbo_pieces"),
  cash_sweep_year: F("Cash sweep", "Debt minus sweep% x free cash flow.", "paper_lbo_pieces"),
  moic_from_irr: F("MOIC from IRR", "(1 + IRR)^years. 2x/5y is 15%, 3x/5y is 25%.", "rule_of_72"),
  exit_multiple_breakeven: F("Break-even exit multiple", "Entry EV / exit EBITDA.", "paper_lbo_pieces"),
  "irr_sensitivity_direction:0": F("IRR: longer hold", "Same multiple over more years: IRR down.", "paper_lbo_pieces"),
  "irr_sensitivity_direction:1": F("IRR: more leverage", "Less equity in for the same out: IRR up, risk up.", "paper_lbo_pieces"),
  "irr_sensitivity_direction:2": F("IRR: higher exit multiple", "Higher exit value: IRR up.", "paper_lbo_pieces"),
  "irr_sensitivity_direction:3": F("IRR: dividend recap", "Cash back earlier: IRR up, MOIC flat.", "paper_lbo_pieces"),
  "irr_sensitivity_direction:4": F("IRR: cash burned on capex", "Less debt paid down: equity IRR down.", "paper_lbo_pieces"),
  value_creation_split: F("Returns attribution", "Gain - growth - paydown = multiple expansion.", "paper_lbo_pieces"),
  // rates and options
  "price_yield_direction:0": F("Rates up, bond price", "Down.", "bonds_fast"),
  "price_yield_direction:1": F("Which falls more: long or short", "The longer bond.", "bonds_fast"),
  "price_yield_direction:2": F("Rates down, bond price", "Up.", "bonds_fast"),
  "price_yield_direction:3": F("Which falls more: low or high coupon", "The low coupon: more of its value is far away.", "bonds_fast"),
  "current_yield:yield": F("Current yield", "Coupon / price.", "bonds_fast"),
  "current_yield:ytm": F("YTM vs current yield", "Below 100: YTM above. Above 100: YTM below.", "bonds_fast"),
  duration_price_change: F("Duration to price change", "Minus duration x yield change.", "bonds_fast"),
  "call_payoff:call": F("Long call profit", "max(S - K, 0) - premium.", "option_payoffs"),
  "call_payoff:put": F("Long put profit", "max(K - S, 0) - premium.", "option_payoffs"),
  "call_payoff:breakeven": F("Call break-even", "Strike + premium.", "option_payoffs"),
  "put_call_parity_number:pvk": F("Parity: PV of strike", "Stock - (call - put).", "option_payoffs"),
  "put_call_parity_number:rate": F("Parity: implied rate", "Strike / PV(strike) - 1.", "option_payoffs"),
  delta_hedge_shares: F("Delta hedge", "Contracts x 100 x delta.", "option_payoffs"),
  // probability and statistics
  "dice_ev:one": F("One die, fair price", "3.5.", "fair_price"),
  "dice_ev:two_sum": F("Two dice sum, fair price", "7. Averages add.", "fair_price"),
  "dice_ev:two_product": F("Two dice product, fair price", "12.25. Independent averages multiply.", "fair_price"),
  "dice_ev:max": F("Higher of two dice, fair price", "4.47. Sum k x (2k - 1) / 36.", "fair_price"),
  "flips_to_first_heads:coin": F("Flips to first heads", "1 / p = 2.", "fair_price"),
  "flips_to_first_heads:die": F("Rolls to first six", "1 / p = 6.", "fair_price"),
  "flips_to_first_heads:biased": F("Tries to first success, biased", "1 / p.", "fair_price"),
  "make_a_market:fair": F("Fair value of dice sum", "3.5 per die.", "fair_price"),
  "make_a_market:bid": F("Bid in a market", "Fair value minus half the width.", "fair_price"),
  "conditional_small:0": F("Sum 8, a six showing", "2 of 5 ways.", "count_the_cases"),
  "conditional_small:1": F("Sum 7, a one showing", "2 of 6 ways.", "count_the_cases"),
  "conditional_small:2": F("At least one six, sum 12", "1 of 11 ways.", "count_the_cases"),
  "conditional_small:3": F("Two children, both boys", "1 of 3: BB, BG, GB.", "count_the_cases"),
  "conditional_small:4": F("Sum 10, a double", "1 of 3 ways.", "count_the_cases"),
  bayes_100: F("Bayes with 1,000 people", "True positives / (true + false positives).", "bayes_crowd"),
  "mean_variance_quick:mean": F("Mean of four returns", "Add, divide by 4.", "spread_and_error"),
  "mean_variance_quick:var": F("Variance of four returns", "Average squared distance from the mean.", "spread_and_error"),
  "standard_error:se": F("Standard error", "sd / sqrt(n).", "spread_and_error"),
  "standard_error:t": F("Standard errors from zero", "mean / (sd / sqrt(n)).", "spread_and_error"),
  "vol_sqrt_time:daily": F("Daily to annual vol", "x sqrt(252), about 16.", "sqrt_time"),
  "vol_sqrt_time:monthly": F("Monthly to annual vol", "x sqrt(12), about 3.46.", "sqrt_time"),
  "sharpe_quick:annual": F("Sharpe ratio", "(return - risk-free) / vol.", "sqrt_time"),
  "sharpe_quick:monthly": F("Annualise a monthly Sharpe", "x sqrt(12).", "sqrt_time"),
  "z_score:z": F("Z-score", "(x - mean) / sd.", "spread_and_error"),
  "z_score:tail": F("Tail from a z-score", "1 sd 16%, 2 sd 2.5%, 3 sd 0.15%, one-sided.", "spread_and_error"),
  "correlation_sign:sign": F("Sign of a correlation", "Above 50% together: positive.", "sqrt_time"),
  "correlation_sign:portfolio": F("Two-asset portfolio vol", "vol x sqrt((1 + correlation) / 2) for equal vols and weights.", "sqrt_time"),
  market_size_steps: F("Market sizing chain", "Population / household x ownership / replacement years.", "fermi_chain"),
  // poker
  pot_odds: F("Pot odds", "call / (pot + call). The pot already includes their bet.", "pot_odds_three_ways"),
  "outs_equity:1": F("Outs, one card to come", "outs x 2, or exactly outs / 46.", "rule_of_4_and_2"),
  "outs_equity:2": F("Outs, two cards to come", "outs x 4, minus (outs - 8) when outs are above 8. Exact: 1 - (miss)(miss).", "rule_of_4_and_2"),
  ev_call: F("EV of a call", "win% x pot minus lose% x call."),
  implied_odds: F("Implied odds", "call / win% is the pot you need; subtract what is there after your call."),
  "combos:pair": F("Combos: pocket pair", "4 choose 2 = 6."),
  "combos:suited": F("Combos: suited hand", "One per suit = 4."),
  "combos:offsuit": F("Combos: offsuit hand", "16 total minus 4 suited = 12."),
  "combos:any": F("Combos: any two ranks", "4 x 4 = 16."),
  "combos:pair_blocked": F("Combos: pair with a blocker", "3 left, choose 2 = 3."),
  "combos:any_blocked": F("Combos: two ranks with a blocker", "3 x 4 = 12."),
  "pot_odds_bet:third": F("Third-pot bet", "bet / (pot + 2 x bet): a third-pot bet needs 20%.", "pot_odds_three_ways"),
  "pot_odds_bet:half": F("Half-pot bet", "bet / (pot + 2 x bet): a half-pot bet needs 25%.", "pot_odds_three_ways"),
  "pot_odds_bet:twothirds": F("Two-thirds to three-quarter pot bet", "bet / (pot + 2 x bet): about 29% to 30%.", "pot_odds_three_ways"),
  "pot_odds_bet:pot": F("Pot-sized bet", "bet / (pot + 2 x bet): a pot-sized bet needs 33%.", "pot_odds_three_ways"),
  "pot_odds_bet:over": F("Overbet", "bet / (pot + 2 x bet): 1.5x pot needs 37.5%, 2x pot needs 40%.", "pot_odds_three_ways"),
  bluff_break_even: F("Bluff break-even", "bet / (pot + bet). Half-pot bluff needs a fold one time in three.", "pot_odds_three_ways"),
  pot_odds_decision: F("Call or fold", "Chance to hit by the rule of 4 and 2 against call / (pot + call). The rule and the exact math always agree here.", "pot_odds_three_ways"),
  // quick
  percent_of: F("Percent of a number", "Take 10%, then scale. 1% for the awkward ones.", "percent_scaling"),
  fraction_to_decimal: F("Fraction to decimal", "Know 1/n, multiply by the top.", "fractions_worth_knowing"),
  "multiply_shortcuts:x11": F("Multiply by 11", "Split the digits, put their sum in the middle, carry if needed.", "multiply_by_11"),
  "multiply_shortcuts:sq5": F("Squares ending in 5", "tens x (tens + 1), then append 25.", "squares_ending_in_5"),
  "multiply_shortcuts:x25": F("Multiply by 25", "Divide by 4, then x 100.", "multiply_by_5_25_50"),
  "growth_rate:pct": F("Growth rate", "change / start.", "percent_scaling"),
  "growth_rate:double": F("Years to double", "72 / rate.", "rule_of_72"),
  "back_of_envelope:multiple": F("EV/EBITDA multiple", "EV / EBITDA.", "multiples_and_yields"),
  "back_of_envelope:ebitda": F("EBITDA from a margin", "revenue x margin.", "percent_scaling"),
  "back_of_envelope:mktcap": F("Market cap", "price x shares.", "millions_and_billions"),
  "back_of_envelope:interest": F("Interest expense", "debt x rate.", "percent_scaling"),
  // banking
  equity_value: F("Equity value from EV", "EV - debt + cash."),
  ev_from_equity: F("EV from market cap", "market cap + debt - cash."),
  multiple_to_yield: F("Multiple to yield", "1 / multiple.", "multiples_and_yields"),
  pe_ratio: F("P/E ratio", "price / EPS.", "multiples_and_yields"),
  dividend_yield: F("Dividend yield", "dividend / price.", "percent_scaling"),
  after_tax_debt: F("After-tax cost of debt", "rate x (1 - tax)."),
  wacc: F("Blended cost of capital", "equity% x cost of equity + debt% x cost of debt x (1 - tax)."),
  capm: F("Cost of equity (CAPM)", "risk-free + beta x premium."),
  discount_one_year: F("Discount one year", "divide by (1 + rate)."),
  perpetuity: F("Perpetuity value", "cash flow / (rate - growth)."),
  lbo_return: F("Buyout yearly return", "Anchors: 2x in 5 years is 15%, 3x in 5 is 25%; rule of 72 for doubling.", "rule_of_72"),
  lbo_moic: F("Buyout multiple", "equity out / equity in."),
  accretion: F("Accretive or dilutive", "All-stock: buyer's P/E above target's is accretive.", "multiples_and_yields"),
  interest_coverage: F("Interest coverage", "EBITDA / interest. Below about 2x is tight, above about 4x is comfortable.", "coverage_ratios"),
  bank_spread: F("Bank spread", "(lend rate - deposit rate) x loans."),
  // accounting
  balance_sheet: F("Balance sheet", "equity = assets - liabilities."),
  eps: F("Earnings per share", "net income / shares."),
  net_income_from_ebit: F("Net income from EBIT", "(EBIT - interest) x (1 - tax)."),
  working_capital: F("Working capital", "current assets - current liabilities."),
  dep_net_income: F("Depreciation up: net income", "falls by amount x (1 - tax)."),
  dep_cash: F("Depreciation up: cash", "rises by amount x tax."),
  // moose / novyx / betting / energy
  contribution_margin: F("Contribution margin ($)", "price - product cost - shipping - fee% of price.", "percent_scaling"),
  "contribution_margin:pct": F("Contribution margin (%)", "margin $ / price.", "percent_scaling"),
  payback_months: F("Payback months", "CAC / (margin per order x orders per month)."),
  break_even_units: F("Break-even units", "fixed costs / margin per unit."),
  discount_trap: F("Discount trap", "margin / (margin - discount) - 1."),
  roas_to_return: F("Ad return", "ROAS x margin - 1."),
  customer_value: F("Customer value", "margin per order x orders."),
  rebooking_revenue: F("Rebooking revenue", "visits x rate x ticket."),
  unrealized_revenue: F("Unrealized revenue", "(target rate - rate) x visits x ticket."),
  rate_card: F("Rate card price", "cost / (1 - margin).", "percent_scaling"),
  pipeline_revenue: F("Pipeline revenue", "leads x close rate x ticket."),
  lifetime_value: F("Lifetime value", "ticket x visits per year x years."),
  american_to_prob: F("American odds to chance", "+odds: 100 / (odds + 100). -odds: odds / (odds + 100)."),
  decimal_to_prob: F("Decimal odds to chance", "1 / odds."),
  fraction_to_decimal_odds: F("Fractional to decimal odds", "top / bottom + 1."),
  remove_vig: F("Remove the vig", "side / (side + other side)."),
  bet_ev: F("EV of a bet", "p x stake x (odds - 1) minus (1 - p) x stake."),
  kelly: F("Kelly fraction", "(p x (odds - 1) - (1 - p)) / (odds - 1)."),
  oil_revenue: F("Quarterly oil revenue", "barrels a day x price x 90.", "millions_and_billions"),
  netback: F("Netback", "price minus costs per barrel."),
  decline: F("Decline", "output x (1 - rate)."),
  reserve_life: F("Reserve life", "reserves / (daily output x 365).", "millions_and_billions"),
  breakeven_price: F("Break-even oil price", "(opex + capex) / (1 - royalty)."),
};
Object.assign(FAMILIES, {
  count_outs: F("Count the outs", "Add the draws, subtract cards counted twice.", "count_the_outs"),
  pot_odds_ratio: F("Pot odds as a ratio", "pot to call; percent is 1 / (ratio + 1).", "pot_odds_three_ways"),
  price_out_draw: F("Pricing out a draw", "bet / (pot + 2 x bet) must beat the draw's chance. Rule of 4 is fine: gutshot about a quarter pot, open-ender about 0.85 pot, flush draw more than the pot.", "price_out_draw"),
  near_100: F("Near-100 products", "front: one number minus the other's gap; back: gaps multiplied.", "near_100"),
  halve_double: F("Halve and double", "halve the even one, double the other.", "halve_and_double"),
  split_multiply: F("Split the hard one", "tens x b, then ones x b, add.", "split_the_hard_one"),
  round_adjust: F("Round, then adjust", "round x b, then add or subtract gap x b.", "round_and_adjust"),
  "divide_shortcuts:d4": F("Divide by 4", "halve twice.", "divide_by_4_and_8"),
  "divide_shortcuts:d8": F("Divide by 8", "halve three times.", "divide_by_4_and_8"),
  "divide_shortcuts:d5": F("Divide by 5", "double, then divide by 10.", "divide_by_5_25_50"),
  "divide_shortcuts:d25": F("Divide by 25", "times 4, then divide by 100.", "divide_by_5_25_50"),
  "divide_shortcuts:d50": F("Divide by 50", "double, then divide by 100.", "divide_by_5_25_50"),
  reverse_percent: F("Reverse percent", "part / (percent as a decimal).", "percent_scaling"),
  percent_chain: F("Percent chain", "multiply (1 + a)(1 + b), then subtract 1.", "percent_scaling"),
  unit_juggle: F("Units: millions and billions", "convert to one unit, multiply the plain numbers, then the units.", "millions_and_billions"),
  accretion_mix: F("Accretion, mixed payment", "target's yield vs blended cost of stock (earnings yield) and after-tax debt.", "multiples_and_yields"),
  synergies_breakeven: F("Break-even synergies", "premium / multiple."),
  dcf_two_year: F("Two-year DCF", "each cash flow / (1 + r)^year, terminal value in the last year."),
  debt_paydown: F("Debt paydown", "debt - paydown x years."),
  cap_table: F("Dilution", "own x pre / (pre + raise)."),
});
const EVENTS = ["Depreciation up: net income", "Depreciation up: cash", "Inventory up: net income", "Inventory up: cash", "Share issue: assets", "Share issue: net income", "New debt: equity", "Dividend: equity", "Dividend: net income", "Interest up: cash", "Receivables up: cash", "Payables up: cash", "Invoice collected: net income", "Factory bought: net income"];
EVENTS.forEach((n, i) => { FAMILIES[`statement_direction:${i}`] = F(n, "Ask which statement the event touches first, then follow it across."); });
