// One-minute methods. Standard techniques only (Benjamin's Secrets of Mental Math, Trachtenberg, interview-prep anchors).
// Each: id, title, families it trains, the method in one sentence, worked examples, when it works, one trap.
export const LESSONS = [
  {
    id: "percent_scaling", title: "Percent: start at 10%, then scale", families: ["percent_of", "growth_rate:pct", "back_of_envelope:ebitda", "back_of_envelope:interest", "dividend_yield", "contribution_margin", "contribution_margin:pct", "rate_card"],
    method: "Find 10% by moving the decimal one place, then build the percent you need from 10%, 5% (half of it), and 1% (a tenth of it).",
    examples: ["15% of 240: 10% is 24, 5% is 12, so 36.", "35% of 80: 10% is 8, so 30% is 24, plus 5% (4) = 28.", "7% of 300: 1% is 3, so 21."],
    when: "Any percent of any number. Also for margins, interest, yields, and growth, which are all \"percent of\" in disguise.",
    trap: "Growth rate divides by the start, not the end. From 80 to 100 is +25%, not +20%.",
  },
  {
    id: "percent_flip", title: "Percent flip: a% of b is b% of a", families: ["percent_of"],
    method: "Swap the two numbers when the other order is easier.",
    examples: ["8% of 25 = 25% of 8 = 2.", "16% of 50 = 50% of 16 = 8.", "12% of 75 = 75% of 12 = 9."],
    when: "Whenever one number is 25, 50, 75, or a clean fraction of 100.",
    trap: "It only swaps the roles; it does not change the answer's units. 8% of $25 is $2.",
  },
  {
    id: "multiply_by_11", title: "Multiply by 11", families: ["multiply_shortcuts:x11"],
    method: "Write the two digits apart and put their sum in the middle; if the sum is 10 or more, carry into the left digit.",
    examples: ["45 x 11: 4 _ 5, middle 9, so 495.", "78 x 11: 7 _ 8, middle 15, carry: 858.", "62 x 11: 6 _ 2, middle 8: 682."],
    when: "Any two-digit number times 11. For three digits, add each neighbouring pair.",
    trap: "Forgetting the carry: 78 x 11 is 858, not 7158.",
  },
  {
    id: "multiply_by_5_25_50", title: "Multiply by 5, 25, and 50", families: ["multiply_shortcuts:x25"],
    method: "By 5: halve, then times 10. By 25: quarter, then times 100. By 50: halve, then times 100.",
    examples: ["46 x 5: 23, then 230.", "36 x 25: 9, then 900.", "18 x 50: 9, then 900."],
    when: "Any of the three. For 15: add half, then times 10 (24 x 15: 24 + 12 = 36, so 360).",
    trap: "Odd numbers halve to a .5; keep it. 47 x 5: 23.5, then 235.",
  },
  {
    id: "squares_ending_in_5", title: "Squares ending in 5", families: ["multiply_shortcuts:sq5"],
    method: "Take the tens digit, multiply by one more than itself, and append 25.",
    examples: ["35 squared: 3 x 4 = 12, so 1225.", "65 squared: 6 x 7 = 42, so 4225.", "95 squared: 9 x 10 = 90, so 9025."],
    when: "Any number ending in 5, including 105 (10 x 11 = 110, so 11025).",
    trap: "It is tens times (tens + 1), not tens squared.",
  },
  {
    id: "near_100", title: "Multiplying numbers near 100", families: ["near_100"],
    method: "Note how far each is below 100. Subtract one gap from the other number for the front, multiply the gaps for the back (two digits).",
    examples: ["97 x 96: gaps 3 and 4. 97 - 4 = 93. 3 x 4 = 12. So 9312.", "98 x 92: gaps 2 and 8. 98 - 8 = 90. 2 x 8 = 16. So 9016.", "94 x 94: gaps 6 and 6. 88 and 36: 8836."],
    when: "Both numbers within about 10 of 100. Works above 100 too, adding instead of subtracting.",
    trap: "The back half is always two digits: 3 x 2 = 06, not 6.",
  },
  {
    id: "halve_and_double", title: "Halve one, double the other", families: ["halve_double"],
    method: "When one number is even, halve it and double the other until the product is easy.",
    examples: ["16 x 35 = 8 x 70 = 560.", "24 x 15 = 12 x 30 = 360.", "14 x 45 = 7 x 90 = 630."],
    when: "One factor even and the other ending in 5, or anything that becomes a round number when doubled.",
    trap: "Halve and double the same number of times, or the product changes.",
  },
  {
    id: "split_the_hard_one", title: "Split the hard one", families: ["split_multiply"],
    method: "Break one factor into tens and ones, multiply each part, and add.",
    examples: ["23 x 7 = 20 x 7 + 3 x 7 = 140 + 21 = 161.", "34 x 6 = 180 + 24 = 204.", "47 x 8 = 320 + 56 = 376."],
    when: "Any two-digit by one-digit product. Say the big part first so you hold less in your head.",
    trap: "Adding before you have both parts. Finish the tens product, hold it, then do the ones.",
  },
  {
    id: "divide_by_5_25_50", title: "Divide by 5, 25, and 50", families: ["divide_shortcuts:d5", "divide_shortcuts:d25", "divide_shortcuts:d50"],
    method: "By 5: double, then divide by 10. By 25: times 4, then divide by 100. By 50: double, then divide by 100.",
    examples: ["345 / 5: 690, then 69.", "275 / 25: 1100, then 11.", "1,350 / 50: 2,700, then 27."],
    when: "Any of the three, including in money: $2,400 across 25 people is 96 each.",
    trap: "Doubling then dividing by 10 is the same as dividing by 5. Do not also halve.",
  },
  {
    id: "divide_by_4_and_8", title: "Divide by 4 and 8", families: ["divide_shortcuts:d4", "divide_shortcuts:d8"],
    method: "Halve twice for 4; halve three times for 8.",
    examples: ["372 / 4: 186, 93.", "1,000 / 8: 500, 250, 125.", "540 / 4: 270, 135."],
    when: "Quarters and eighths of anything: quarterly numbers from a yearly figure, EV/EBITDA at 8x.",
    trap: "Odd halves are fine: 93 / 2 = 46.5. Keep going.",
  },
  {
    id: "fractions_worth_knowing", title: "Fractions worth knowing cold", families: ["fraction_to_decimal"],
    method: "Memorise 1/n for n up to 12 and for 16, then multiply by the top.",
    examples: ["1/7 = 0.143, 1/8 = 0.125, 1/9 = 0.111, 1/11 = 0.0909, 1/12 = 0.0833, 1/16 = 0.0625.", "5/8 = 5 x 0.125 = 0.625.", "3/7 = 3 x 0.143 = 0.429."],
    when: "Ratios, odds, and quick shares: 3 to 1 pot odds is 1/4 = 25%.",
    trap: "Sevenths repeat in a cycle: 1/7 = 0.142857. Three decimals is enough for any drill here.",
  },
  {
    id: "round_and_adjust", title: "Round, then adjust", families: ["round_adjust"],
    method: "Multiply by the nearest round number, then subtract or add the difference.",
    examples: ["49 x 6 = 300 - 6 = 294.", "19 x 7 = 140 - 7 = 133.", "31 x 8 = 240 + 8 = 248."],
    when: "One factor ends in 9, 8, 1, or 2.",
    trap: "The adjustment is the other factor times the gap: 48 x 6 = 300 - 12, not 300 - 2.",
  },
  {
    id: "millions_and_billions", title: "Millions and billions without losing zeros", families: ["back_of_envelope:mktcap", "oil_revenue", "reserve_life", "unit_juggle"],
    method: "Name the unit of each number, multiply the plain numbers, then multiply the units: M x M is trillions; M x thousands is billions; per-day x 365 is per year.",
    examples: ["$50 x 500M shares = 25,000M = $25B.", "10,000 barrels a day x $70 x 90 days = 63,000,000 = $63M a quarter. Shortcut: barrels a day x price x 0.09 gives $M a quarter.", "$1.2B / 40M shares = $30 a share.", "Anchor: $365M a year is $1M a day."],
    when: "Market caps, revenue from a daily rate, per-share numbers.",
    trap: "Dividing millions by millions gives a plain number; dividing millions by thousands gives thousands. Say the units out loud.",
  },
  {
    id: "rule_of_72", title: "Rule of 72 and the doubling anchors", families: ["growth_rate:double", "lbo_return", "moic_from_irr"],
    method: "Years to double is about 72 divided by the yearly rate. For a buyout: 2x in 5 years is about 15% a year, 3x in 5 years about 25%, 2x in 3 years about 26%.",
    examples: ["9% a year doubles in 8 years.", "Doubled in 4 years: about 18% a year.", "3x in 5 years: 25%. 2.5x in 5 years: about 20%."],
    when: "Any compounding question asked out loud. Interviewers want the anchor, not the exact power.",
    trap: "The rule of 72 is for doubling only. For tripling, 114 / rate is the equivalent.",
  },
  {
    id: "multiples_and_yields", title: "Multiples and yields are the same fact", families: ["multiple_to_yield", "pe_ratio", "back_of_envelope:multiple", "accretion"],
    method: "A multiple is price over earnings; a yield is earnings over price. Flip one to get the other.",
    examples: ["20x earnings is a 5% earnings yield.", "10x EBITDA is a 10% EBITDA yield.", "A 4% yield is a 25x multiple."],
    when: "Comparing to interest rates, and for accretion: buying a higher yield with a lower one adds to earnings per share.",
    trap: "A high multiple means expensive, a high yield means cheap. They move opposite ways.",
  },
  {
    id: "pot_odds_three_ways", title: "Pot odds three ways", families: ["pot_odds", "pot_odds_ratio", "pot_odds_bet:third", "pot_odds_bet:half", "pot_odds_bet:twothirds", "pot_odds_bet:pot", "pot_odds_bet:over", "bluff_break_even", "pot_odds_decision"],
    method: "Percent: call / (pot + call). Ratio: pot to call, and 1 / (ratio + 1) is the same percent. When the pot is stated before the bet: bet / (pot + 2 x bet).",
    examples: ["$10 to call into $30: 10 / 40 = 25%. As a ratio, 3 to 1.", "Third-pot bet: 20%. Half-pot: 25%. Two-thirds: 29%. Pot-sized: 33%. One and a half pot: 1.5 / 4 = 37.5%.", "Bluffing $50 into $100: it works if they fold 50 / 150 = 33% of the time. A pot-sized bluff needs them to fold half the time.", "Call or fold: compare your chance from the rule of 4 and 2 with the pot-odds number. In this app the drills never sit so close that the rule and the exact math disagree."],
    when: "Every call decision. Ask \"before or after the bet?\" before you answer.",
    trap: "Mixing the two pots. $100 pot, $50 bet: it is 50 / 200 = 25%, not 50 / 150.",
  },
  {
    id: "rule_of_4_and_2", title: "Rule of 4 and 2, with the correction", families: ["outs_equity:1", "outs_equity:2"],
    method: "Two cards to come: outs x 4. One card: outs x 2. Above 8 outs with two cards to come, subtract (outs - 8) from the rule-of-4 number.",
    examples: ["9 outs: 36 - 1 = 35% (exact 34.97). One card: 18% (exact 19.6).", "15 outs: 60 - 7 = 53% (exact 54).", "4 outs: 16% and 8% (exact 16.5 and 8.7)."],
    when: "Any draw. Know 9 outs (flush draw) and 8 outs (open-ended) cold; the rest you derive. In every drill here, the plain rule, the corrected rule, and the exact number are all marked correct.",
    trap: "Rule of 4 assumes you see both cards. If a bet on the turn will price you out, use the rule of 2 for the next card only.",
  },
  {
    id: "price_out_draw", title: "Pricing out a draw", families: ["price_out_draw"],
    method: "Your bet b gives them b / (pot + 2b). Set that above their chance of hitting and solve: b > chance x pot / (1 - 2 x chance).",
    examples: ["Gutshot, 4 outs, both cards for one bet: about 16%, so b > 0.16 / 0.68 = about a quarter pot.", "Open-ended, 8 outs: about 32%, so b > 0.32 / 0.36 = about 0.85 pot.", "Flush draw, 9 outs: about 35%, so b > 0.35 / 0.30 = more than the pot. With one card to come it is about 20%, and a third of the pot does it."],
    when: "When you are ahead and want a drawing opponent to make a mistake by calling. The rule of 4 is accurate enough; the drills accept it.",
    trap: "Assuming they see both cards for one bet. If you bet again on the turn, price each street with the rule of 2 instead.",
  },
  {
    id: "coverage_ratios", title: "Interest coverage at a glance", families: ["interest_coverage"],
    method: "Coverage = EBITDA / interest. It says how many times over the business can pay its interest.",
    examples: ["EBITDA 100, interest 25: 4x.", "Below about 2x, lenders get nervous. Above about 4x is comfortable.", "Leverage is the flip side: debt / EBITDA. 5x leverage at 8% interest is coverage of 1 / (5 x 0.08) = 2.5x."],
    when: "Credit questions, buyout debt sizing, and any \"can this company take more debt?\" question.",
    trap: "Using net income or EBIT when the question says EBITDA. Say which one you used.",
  },
  {
    id: "count_the_outs", title: "Count the outs", families: ["count_outs"],
    method: "Add the cards that complete each draw, and subtract any card counted twice.",
    examples: ["Flush draw: 9 (13 of the suit minus the 4 you see).", "Open-ended straight: 8. Gutshot: 4. Two overcards: 6.", "Flush draw plus open-ended: 9 + 8 - 2 (the two straight cards that are also the suit) = 15."],
    when: "Before every pot-odds calculation. The outs number is the input to everything else.",
    trap: "Dirty outs: a card that makes your straight but also makes someone else's flush is not a full out. Discount it.",
  },
  // ---------- quant and financial math ----------
  {
    id: "ufcf_build", title: "Unlevered free cash flow in four moves", families: ["ufcf"],
    method: "Start at EBIT, take off tax as if there were no debt, add back D&A because it is not cash, subtract capex, subtract any cash tied up in working capital.",
    examples: ["EBIT 200, tax 25%: 150. Plus D&A 40 = 190. Minus capex 50 = 140. Minus 10 of working-capital growth = 130.", "If working capital shrinks, add it: cash came out of inventory or receivables.", "Say it as a sentence: profit after tax, add back the non-cash, take off what you reinvested."],
    when: "Any DCF question, and \"walk me through a DCF\" starts here. Unlevered means before interest, so the same number serves every capital structure.",
    trap: "Taxing EBIT, not EBT. Interest is left out on purpose, so the tax is higher than the real tax bill.",
  },
  {
    id: "terminal_value_two_ways", title: "Terminal value two ways, and the cross-check", families: ["perpetuity", "dcf_two_year", "tv_exit_multiple", "tv_perpetuity_vs_exit", "implied_growth", "mid_year_direction:0", "mid_year_direction:1", "mid_year_direction:2"],
    method: "Exit multiple: final EBITDA x the peer multiple. Perpetuity: final cash flow x (1 + g) / (rate - g). Compute both, then back out what one implies about the other.",
    examples: ["EBITDA 100 x 8 = 800. FCF 60, rate 10%, growth 3%: 61.8 / 0.07 = 883. Close enough to trust.", "Implied growth from a multiple: g = (TV x r - FCF) / (TV + FCF). TV 800, r 10%, FCF 50: 30 / 850 = 3.5%.", "Mid-year: each flow is discounted half a year less, so value rises, by about 5% at a 10% rate."],
    when: "Every DCF ends with a terminal value, and it is usually most of the total, which is why the rate and growth assumptions matter so much. Interviewers ask which method you used and why the two disagree.",
    trap: "Growth above the rate, or near it. The perpetuity formula explodes as g approaches r. Long-run growth above about 4% is a red flag.",
  },
  {
    id: "comps_chain", title: "The comps chain: multiple to share price", families: ["comps_implied_ev", "multiple_translate", "pe_from_ev_ebitda"],
    method: "Multiple x the target's metric gives enterprise value. Subtract net debt for equity value. Divide by shares for a price. To switch multiples, use the margin as the exchange rate.",
    examples: ["10x on 150 of EBITDA = 1,500. Minus 300 net debt = 1,200. Over 50M shares = $24.", "EV/Revenue 2x at a 25% margin is 2 / 0.25 = 8x EBITDA.", "8x on 100 EBITDA = 800 EV. Minus 200 net debt = 600 equity. Over 40 of net income: P/E 15x."],
    when: "Any \"what is this company worth by comps\" question. Say each step as you go; the interviewer is checking the chain, not the arithmetic.",
    trap: "Mixing the two families. EV multiples go with EBITDA and revenue (before interest); P/E goes with net income (after interest). Net debt is the bridge, and it goes one way only.",
  },
  {
    id: "three_statement_walk", title: "One event, three statements", families: ["walk_depreciation_cash", "walk_inventory_writedown:cash", "walk_inventory_writedown:equity", "walk_sell_inventory:ni", "walk_sell_inventory:cash", "walk_capex_cash:cash", "walk_capex_cash:ni", "walk_debt_raise", "walk_buyback:0", "walk_buyback:1", "walk_buyback:2"],
    method: "Income statement first: what hits profit, after tax. Cash flow second: start from that net income, add back anything non-cash, then investing and financing. Balance sheet last: cash on one side, retained earnings plus whatever moved on the other.",
    examples: ["Depreciation up 10 at 40% tax: NI down 6, add back 10, cash up 4. PP&E down 10, cash up 4, equity down 6.", "Write down 20 of inventory at 25%: NI down 15, add back 20, cash up 5. Inventory down 20, cash up 5, equity down 15.", "Buy back 50 of stock: income statement untouched. Cash down 50, equity down 50. Fewer shares, so EPS up."],
    when: "The most common accounting question in a first round. Always say the tax effect; it is what separates a memorised answer from an understood one.",
    trap: "Forgetting that a non-cash charge still saves real tax. The cash effect of a write-down is positive, which surprises people the first time.",
  },
  {
    id: "paper_lbo_pieces", title: "The paper LBO in pieces", families: ["sources_uses_equity", "leverage_turns:total", "leverage_turns:rate", "cash_sweep_year", "exit_multiple_breakeven", "irr_sensitivity_direction:0", "irr_sensitivity_direction:1", "irr_sensitivity_direction:2", "irr_sensitivity_direction:3", "irr_sensitivity_direction:4", "value_creation_split"],
    method: "Uses = price + fees. Sources = debt (turns x EBITDA) + equity, so equity is the plug. Each year, spare cash sweeps down the debt. At exit: multiple x EBITDA, minus what is left of the debt, is the equity out. Equity out over equity in is the MOIC.",
    examples: ["10x on 100 EBITDA, 5x debt, 30 of fees: uses 1,030, debt 500, equity 530.", "Debt 500, FCF 60, full sweep: 440 after year one.", "Entry 10x on 100; EBITDA to 130. Same EV needs only 1,000 / 130 = 7.7x at exit. Any exit above that and growth has paid."],
    when: "Private equity interviews, and the superday version of the IB buyout question. Three things create value: EBITDA growth, debt paydown, multiple expansion. Attribute the gain to them and you have answered the follow-up too.",
    trap: "Treating leverage as free. More debt raises the equity IRR when it works and wipes the equity out when it does not; say both halves.",
  },
  {
    id: "bonds_fast", title: "Bonds the fast way", families: ["price_yield_direction:0", "price_yield_direction:1", "price_yield_direction:2", "price_yield_direction:3", "current_yield:yield", "current_yield:ytm", "duration_price_change"],
    method: "Price and yield move opposite ways. Current yield is coupon over price. Below 100 the yield to maturity is above the current yield; above 100 it is below. Duration times the yield change, with a minus sign, is the price change.",
    examples: ["6% coupon at 120: current yield 5%, and YTM below 5% because you lose 20 at maturity.", "Duration 7, yields up 50bp: price down about 3.5%.", "Rates up: the 30-year falls more than the 2-year, and the 2% coupon falls more than the 8%."],
    when: "Markets questions, S&T interviews, and any time someone says \"rates went up\" and expects you to know what happened to bonds.",
    trap: "Duration is a straight-line guess. For big moves the true curve bends in the bondholder's favour (convexity), so the real loss is a bit smaller than duration says.",
  },
  {
    id: "option_payoffs", title: "Option payoffs, and parity from the picture", families: ["call_payoff:call", "call_payoff:put", "call_payoff:breakeven", "put_call_parity_number:pvk", "put_call_parity_number:rate", "delta_hedge_shares"],
    method: "At expiry a call is worth max(stock - strike, 0) and a put max(strike - stock, 0); profit subtracts the premium. Long call plus short put, same strike, draws the same line as owning the stock and owing the strike, so call - put = stock - PV(strike). Delta is the slope of the option's value and, roughly, the chance it finishes in the money. Contracts x 100 x delta is your share exposure.",
    examples: ["50-strike call for 3, stock ends at 58: 8 - 3 = 5. Break-even 53.", "Stock 100, call 8, put 5: PV(strike) = 100 - 3 = 97, so the one-year rate is about 3%.", "20 contracts, delta 0.4: 20 x 100 x 0.4 = 800 shares to sell."],
    when: "Trading interviews. Draw the four payoff lines (long call, short put, long stock, a flat line at minus the strike) and parity is obvious, no formula needed.",
    trap: "Forgetting the premium. The payoff is what the option is worth; the profit is that minus what you paid.",
  },
  {
    id: "fair_price", title: "Fair price of a game", families: ["dice_ev:one", "dice_ev:two_sum", "dice_ev:two_product", "dice_ev:max", "flips_to_first_heads:coin", "flips_to_first_heads:die", "flips_to_first_heads:biased", "make_a_market:fair", "make_a_market:bid"],
    method: "Fair price is the expected payout. Averages add. For independent things, averages multiply. Tries to a first success average 1 / p. To make a market, quote a bid below fair and an offer above it.",
    examples: ["One die: 3.5. Two dice sum: 7. Two dice product: 12.25.", "Coin until heads: 2 flips. Die until a six: 6 rolls.", "Three dice sum, fair 10.5, a 2-wide market: 9.5 bid, 11.5 offered."],
    when: "Every trading-interview brainteaser starts here. Say the fair value first, then the market; the width is your confidence.",
    trap: "The higher of two dice is not 3.5 and not 7. Count it: P(max = k) = (2k - 1) / 36, and the answer is 161 / 36 = 4.47. And two heads in a row is a different question from the first heads: it takes 6 flips on average, not 2.",
  },
  {
    id: "count_the_cases", title: "Conditional probability by counting", families: ["conditional_small:0", "conditional_small:1", "conditional_small:2", "conditional_small:3", "conditional_small:4"],
    method: "Write down every outcome that fits the condition. Count the ones you want. Divide.",
    examples: ["Two dice sum to 8: (2,6)(3,5)(4,4)(5,3)(6,2). Two have a six: 2 / 5.", "At least one six: 11 outcomes, not 12, because (6,6) is one outcome. Sum 12 is one of them: 1 / 11.", "Two children, at least one boy: BB, BG, GB. Both boys: 1 / 3."],
    when: "Small dice, coin, and card questions. If the list fits on a napkin, list it; the formula is for when it does not.",
    trap: "Double-counting the double. (6,6) appears once, so \"at least one six\" is 11 cases, not 12.",
  },
  {
    id: "bayes_crowd", title: "Bayes with a crowd of 1,000", families: ["bayes_100"],
    method: "Imagine 1,000 people. Split them into sick and healthy by the base rate. Apply the test to each group to count true positives and false positives. The answer is true positives over all positives.",
    examples: ["1 in 100 sick, 90% caught, 10% false positive: 10 sick, 9 caught; 990 healthy, 99 false alarms. 9 / 108 = 8.3%.", "Raise the base rate to 10 in 100: 90 / (90 + 90) = 50%.", "Cut the false-positive rate to 1%: 9 / (9 + 9.9) = 48%."],
    when: "Any \"you tested positive, what is the chance\" question, and the same logic for a trading signal that fires on a rare event.",
    trap: "Answering with the test's accuracy. A 90% accurate test on a 1% condition is wrong most of the time it says yes.",
  },
  {
    id: "spread_and_error", title: "Mean, variance, standard error, z", families: ["mean_variance_quick:mean", "mean_variance_quick:var", "standard_error:se", "standard_error:t", "z_score:z", "z_score:tail"],
    method: "Mean: add and divide. Variance: average squared distance from the mean; its square root is the standard deviation. Standard error of the mean: sd / sqrt(n). Z: (x - mean) / sd. The 68-95-99.7 rule: within 1, 2, 3 sd of the mean. Halved for one side, the tails are 1 sd 16%, 2 sd 2.5%, 3 sd 0.15%. Two standard errors from zero is the usual bar for \"probably real\".",
    examples: ["Returns 10, -5, 4, -1: mean 2. Squared distances 64, 49, 4, 9 = 126, / 4 = 31.5. Sd 5.6.", "Sd 4% over 36 months: SE 4 / 6 = 0.67%. A 1% mean is 1.5 standard errors from zero: not yet convincing.", "Mean 5, sd 10, month at -15: z = -2, about 2.5% of months this bad if returns were normal."],
    when: "Judging a backtest or a track record. The standard error is the question \"could this be luck?\" in one number.",
    trap: "Sample versus population variance. Dividing by n - 1 instead of n matters for small samples; say which one you used.",
  },
  {
    id: "sqrt_time", title: "Square root of time, Sharpe, and correlation", families: ["vol_sqrt_time:daily", "vol_sqrt_time:monthly", "sharpe_quick:annual", "sharpe_quick:monthly", "correlation_sign:sign", "correlation_sign:portfolio"],
    method: "Independent moves add in variance, so volatility grows with the square root of time: daily x 16 (sqrt of 252), monthly x 3.46 (sqrt of 12). Sharpe = (return - risk-free) / vol, and a monthly Sharpe annualises by sqrt(12). For two equal-vol assets in equal weights, portfolio vol = vol x sqrt((1 + correlation) / 2).",
    examples: ["Daily vol 1%: annual about 16%.", "Return 12%, risk-free 4%, vol 16%: Sharpe 0.5. Monthly Sharpe 0.3: annual 1.04.", "Two assets at 10% vol, correlation 0: portfolio vol 7.1%. Correlation 1: 10%. Correlation -1: zero."],
    when: "Any question about a strategy's risk or its track record, and the first question anyone asks about a backtest. Sharpe bands: below 0.5 is ordinary, 1 is good, above 2 is suspicious until proven. Correlation 0 between two equal assets cuts volatility by about 30%.",
    trap: "Multiplying vol by 252 instead of its square root. Variance scales with time; volatility does not.",
  },
  {
    id: "fermi_chain", title: "Market sizing as a chain", families: ["market_size_steps"],
    method: "Start from a number you know (population), convert step by step (per household, ownership, replacement rate), and say which link is weakest.",
    examples: ["330M people / 2.5 per household = 132M households. 60% own a car: 79M. Replaced every 12 years: 6.6M a year.", "Real US car sales are about 15M: the weak link is one car per household.", "Say the answer as a range, then the reason it could be off."],
    when: "Consulting-style and some banking superday questions. The grade is for the method and the self-correction, not the number.",
    trap: "Precision. Round every step to one or two digits, or you lose the thread by step three.",
  },
];
export const LESSON_BY_ID = Object.fromEntries(LESSONS.map((l) => [l.id, l]));
export const LESSON_BY_FAMILY = {};
for (const l of LESSONS) for (const f of l.families) LESSON_BY_FAMILY[f] = l.id;
